[build]
  publish = "public"
  functions = ".netlify/functions"

[functions]
  directory = ".netlify/functions"

[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/api/auth/register"
  to = "/.netlify/functions/register"
  status = 200

[[redirects]]
  from = "/api/products"
  to = "/.netlify/functions/products"
  status = 200

[[redirects]]
  from = "/api/farmers"
  to = "/.netlify/functions/farmers"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
